[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shape-calculator"
version = "1.0.0"
authors = [
  { name="Nadezhda Shiryaeva", email="sagitova.nadya@mail.ru" },
]
description = "A library to calculate the area of geometric shapes."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
"Homepage" = "https://github.com/DalekTek/shape_calculator_lib"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]